import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Project details · Financial Product Recommender",
  description:
    "What the Financial Product Recommender does, how it works, its measured results and the tech behind it: eligibility rules first, a ranking model second, every reason traceable.",
};

const TECH_BADGES = ["Python", "scikit-learn", "pandas", "FastAPI", "Next.js", "React", "TypeScript", "TanStack Query", "AWS SageMaker", "AWS Lambda"];

const FEATURES = [
  "Pick a customer (or search 1,200 synthetic profiles) and see their top 5 product recommendations, each with plain-language reasons.",
  "Play “what if”: change income, risk profile, employment or age and watch eligibility and the ranking update instantly.",
  "See which products were excluded and exactly which rule each one failed, using the customer’s actual values.",
  "Compare against a “no eligibility layer” view that shows what the same model would recommend without the rules, with rule breaches in red.",
  "Hover any reason to see the data behind it, and check the model’s evaluation and learned weights in a side panel.",
  "Click “Learn more” or “Apply” to log feedback, then retrain the model on it from the browser.",
];

const PIPELINE = [
  { step: "Data", detail: "Customer profiles, a 20-product catalog and view / learn / apply history, loaded and mapped to one internal schema." },
  { step: "Eligibility rules", detail: "Hard, versioned rules (minimum income, risk suitability) decide which products may be shown at all. Missing data never counts as eligible." },
  { step: "Candidates & features", detail: "Only eligible products become candidates; point-in-time profile, product and history features are built for each." },
  { step: "Ranker", detail: "A logistic-regression model scores the candidates by how likely the customer is to apply; the top 5 are kept." },
  { step: "Explanations", detail: "Code builds each reason from one piece of evidence (history, popularity, a rule or the profile) and returns that evidence with it." },
  { step: "API", detail: "A FastAPI service serves recommendations, eligibility checks, model info and feedback, logging a request ID and model and rule versions for every response." },
  { step: "UI", detail: "This Next.js app calls the API and shows recommendations, exclusions, the comparison view and the model panel." },
];

const HIGHLIGHTS = [
  {
    title: "Rules before the model, never inside it",
    detail:
      "Eligibility runs before ranking, locally and in the cloud endpoint. Without it, the same model showed an ineligible product in 22.99% of test requests, even though it was trained only on eligible products.",
  },
  {
    title: "Every reason is checked against the data",
    detail:
      "Explanations are generated by code, not guessed from model weights. An automated check re-verified 3,326 displayed reasons for 200 users against source data, with 0 unsupported.",
  },
  {
    title: "Honest evaluation with a random baseline",
    detail:
      "A time-based holdout compares four strategies, including random and popularity baselines. Because behaviour in this synthetic data barely depends on the profile, the ranker is at chance level, and the page reports that rather than hiding it.",
  },
  {
    title: "Rules derived from the data",
    detail:
      "The two rules were chosen because no logged event breaks them; 0 test applications were for products the rules exclude.",
  },
  {
    title: "Audit trail with data minimisation",
    detail:
      "Each recommendation is logged with its request ID, strategy, model version and rules version. The customer’s financial profile is not written to the log.",
  },
];

const STACK = [
  { group: "Machine learning", items: ["Python", "scikit-learn (logistic regression)", "pandas", "NumPy", "joblib", "Jupyter"] },
  { group: "Backend", items: ["FastAPI", "Pydantic", "Uvicorn", "pytest"] },
  { group: "Frontend", items: ["Next.js (App Router)", "React", "TypeScript", "TanStack Query", "Plain CSS with light/dark themes"] },
  { group: "Cloud (AWS design)", items: ["S3", "SageMaker training & endpoint", "API Gateway", "Lambda", "Kinesis"] },
];

/** Static "Project details" page for portfolio visitors. No API calls, so it renders even if the backend is down. */
export default function AboutPage() {
  return (
    <div className="page about-page">
      <header className="site-header">
        <div className="brand">
          <span className="brand-mark" aria-hidden="true">F</span>
          <div>
            <p className="muted small">Project details</p>
            <h1>Financial Product Recommender</h1>
          </div>
        </div>
        <Link href="/" className="header-link">
          ← Back to the app
        </Link>
      </header>

      <section className="panel about-hero">
        <p className="about-lead">
          A recommender that suggests suitable financial products to each customer. Hard eligibility rules decide what
          may be shown, a machine-learning model ranks what is left, and every reason on screen is traceable to data.
        </p>
        <ul className="about-badges" aria-label="Tech stack">
          {TECH_BADGES.map((badge) => (
            <li key={badge} className="tag tag-accent">
              {badge}
            </li>
          ))}
        </ul>
      </section>

      <p className="disclaimer" role="note">
        Learning project on synthetic data. Not financial advice, a credit decision or real bank eligibility policy.
      </p>

      <div className="about-grid">
        <section className="panel">
          <h2 className="section-title">The problem</h2>
          <p>
            Banks want to suggest relevant products, but some products must never be offered to some customers, for
            example a loan above someone’s income or a high-risk investment to a cautious saver. A ranking model alone
            cannot guarantee that, and customers and regulators expect to know why something was recommended.
          </p>
        </section>

        <section className="panel">
          <h2 className="section-title">What it does</h2>
          <ul className="about-list">
            {FEATURES.map((feature) => (
              <li key={feature}>{feature}</li>
            ))}
          </ul>
        </section>
      </div>

      <section className="panel about-section">
        <h2 className="section-title">How it works</h2>
        <ol className="about-steps">
          {PIPELINE.map((stage, index) => (
            <li key={stage.step}>
              <span className="about-step-number" aria-hidden="true">{index + 1}</span>
              <div>
                <strong>{stage.step}</strong>
                <p className="muted small">{stage.detail}</p>
              </div>
            </li>
          ))}
        </ol>
        <p className="small">
          <strong>On AWS:</strong> data in S3, training and inference on SageMaker (with the eligibility rules running
          inside the endpoint, before ranking), API Gateway and Lambda in front of the endpoint, and feedback events
          streamed through Lambda to Kinesis. No AWS credentials ever reach the browser.
        </p>
      </section>

      <section className="panel about-section">
        <h2 className="section-title">Results</h2>
        <p className="muted small">
          Time-based holdout: trained on the earliest 80% of events, then the full catalog was ranked for each of the
          174 applications in the latest 20% (top 5 shown). Synthetic data: 1,200 users, 20 products, 8,585 interactions.
        </p>
        <div className="about-stats">
          <div className="about-stat stat-ok">
            <strong>0%</strong>
            <span>ineligible products shown with the eligibility layer</span>
          </div>
          <div className="about-stat stat-danger">
            <strong>22.99%</strong>
            <span>of test requests showed an ineligible product when the same model ran without the rules (5.4% of slots)</span>
          </div>
          <div className="about-stat stat-ok">
            <strong>3,326 / 0</strong>
            <span>displayed reasons re-checked against source data / unsupported</span>
          </div>
          <div className="about-stat">
            <strong>0.2701</strong>
            <span>Recall@5 for eligibility → ranker (random baseline: 0.2701)</span>
          </div>
          <div className="about-stat">
            <strong>0.1526</strong>
            <span>NDCG@5 for eligibility → ranker (random baseline: 0.1372)</span>
          </div>
          <div className="about-stat">
            <strong>18.48</strong>
            <span>eligible products per customer on average, out of 20</span>
          </div>
        </div>
        <p className="muted small">
          Read the relevance numbers as a correctly measured null result: every strategy is at chance on this synthetic
          data. The result that matters is the policy one: the rule layer is what keeps ineligible products out.
        </p>
      </section>

      <div className="about-grid">
        <section className="panel">
          <h2 className="section-title">Engineering highlights</h2>
          <ul className="about-highlights">
            {HIGHLIGHTS.map((highlight) => (
              <li key={highlight.title}>
                <strong>{highlight.title}</strong>
                <p className="muted small">{highlight.detail}</p>
              </li>
            ))}
          </ul>
        </section>

        <section className="panel">
          <h2 className="section-title">Tech stack</h2>
          <dl className="about-stack">
            {STACK.map((stackGroup) => (
              <div key={stackGroup.group}>
                <dt>{stackGroup.group}</dt>
                <dd>
                  {stackGroup.items.map((item) => (
                    <span key={item} className="tag tag-accent">
                      {item}
                    </span>
                  ))}
                </dd>
              </div>
            ))}
          </dl>
        </section>
      </div>

      <section className="panel about-section">
        <h2 className="section-title">Run it locally</h2>
        <pre className="about-code">
          <code>{`cd backend
python3 -m venv .venv && source .venv/bin/activate
pip install -r requirements-dev.txt
python -m src.train                          # train + evaluate
python -m pytest -q                          # tests
uvicorn api.main:app --reload --port 8004    # API, Swagger at /docs

cd ../frontend
npm install && cp .env.example .env.local
npm run dev                                  # http://localhost:3004`}</code>
        </pre>
      </section>

      <p className="about-footer">
        <Link href="/" className="header-link">
          ← Back to the app
        </Link>
      </p>
    </div>
  );
}
